version: '3.9'

services:
  baracholchik-bot:
    container_name: baracholchik-bot
    build:
      context: ./baracholchik-bot
      dockerfile: Dockerfile
    env_file:
      - ./baracholchik-bot/.env
    volumes:
      - bot_data:/app/data
    restart: unless-stopped
    tty: true
    stdin_open: true

  baracholchik-spy:
    container_name: baracholchik-spy
    build:
      context: ./baracholchik-spy
      dockerfile: Dockerfile
    env_file:
      - ./baracholchik-spy/.env
    volumes:
      - spybot_data:/app/data
      - spybot_sessions:/app/sessions
    restart: unless-stopped
    tty: true
    stdin_open: true
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('ok')"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  bot_data:
  spybot_data:
  spybot_sessions: